# Generated by Django 5.1.1 on 2024-10-04 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedidos', '0002_remove_proveedor_contacto_proveedor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetalle',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_pedidos.pedido'),
        ),
    ]
