# Generated by Django 5.1.1 on 2024-10-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedidos', '0004_pedidodetalle_costo_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidodetalle',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
