# Generated by Django 5.1.1 on 2024-10-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_pedidos', '0003_alter_pedidodetalle_pedido'),
        ('app_ventas', '0008_alter_ventadetalle_producto_venta_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(default='Pedido', max_length=100)),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egreso', to='app_pedidos.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingreso', to='app_ventas.venta')),
            ],
        ),
    ]
