# Generated by Django 5.1.1 on 2024-11-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='tipo',
            field=models.CharField(choices=[('pedido', 'Pedido'), ('personalizado', 'Personalizado')], default='pedido', max_length=15),
        ),
    ]
