# Generated by Django 5.1.1 on 2024-11-06 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finanzas', '0002_egreso_tipo'),
        ('app_ventas', '0008_alter_ventadetalle_producto_venta_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='tipo',
            field=models.CharField(choices=[('venta', 'Venta'), ('personalizado', 'Personalizado')], default='venta', max_length=15),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingreso', to='app_ventas.venta'),
        ),
    ]
